markdown: rdiscount
pygments: true
permalink: /articles/:title
auto: true
rdiscount:
  extensions: [smart]

name: Sayansho LTD
url: http://help.sayansho.com
description: Sayansho help
twitter: sayansho
github: sayansho
gravatar_url: http://www.gravatar.com/avatar/38819aebb11b545fa0eeebc6e772c585.png